import Base from "@/Components/Base";
import "./globals.css";

export const metadata = {
  title: "admin dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='antialiased bg-[#121212] text-white'
      >
        <Base>{children}</Base>
      </body>
    </html>
  );
}
